Use sklearn.datasets iris flower dataset to train your model using logistic regression. You need to figure out accuracy of your model and use that to predict different samples in your test dataset. In iris dataset there are 150 samples containing following features,

1)Sepal Length   
2)Sepal Width  
3)Petal Length  
4)Petal Width  

Using above 4 features you will clasify a flower in one of the three categories,

Setosa  
Versicolour  
Virginica

<img src="iris_petal_sepal.png" alt="Image Alt Text" width="300">


In [124]:
import numpy as np
from sklearn.datasets import load_iris
%matplotlib inline
import matplotlib.pyplot as plt
flowers = load_iris()

In [125]:
 flowers

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [126]:
dir(flowers)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [144]:
flowers.data[0]
data_point_2d = data_point.reshape(1, -1)

In [128]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=2000)

In [129]:
from sklearn.model_selection import train_test_split


In [130]:
X_train, X_test, y_train, y_test = train_test_split(flowers.data,flowers.target, test_size=0.2)


In [131]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [132]:
model.score(X_test, y_test)

0.9666666666666667

In [133]:
X_train.shape

(120, 4)

In [134]:
X_test.shape

(30, 4)

In [135]:
model.predict(X_test)                 

array([1, 0, 2, 2, 0, 0, 1, 2, 1, 2, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 0, 0,
       1, 0, 2, 0, 0, 1, 2, 0])

In [136]:
flowers.target_names                            #class_labels = flowers.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [137]:
model.predict([[5.1, 3.5, 1.4, 0.2]])           #predicted_class = model.predict([[5.1, 3.5, 1.4, 0.2]])

array([0])

In [138]:
flowers.target_names[model.predict([[5.1, 3.5, 1.4, 0.2]])]        # predicted_class_label = class_labels[predicted_class[0]]

array(['setosa'], dtype='<U10')

In [141]:
model.predict([[7.2, 3.2, 6.0, 1.8]])

array([2])

In [148]:
class_labels[2]

'virginica'